### PR TITLE
Allow React@16+

### PR DESCRIPTION
**Pull request by hawkrives**
I opted to mirror the `>=` from the react peerDep.

### CODE REVIEW

**Comment by bgeihsgt** [comment]
@chenglou can you please approve/merge this change? It's causing peer dependency warnings in our build and we'd like not to rely on our fork that's working around this problem.

**Comment by chenglou** [comment]
There we go

**Comment by chenglou** [comment]
The devDeps haven't been bumped. I'll bump them too

**Comment by chenglou** [comment]
Published

**Comment by bgeihsgt** [comment]
Thank you very much!

**Pull request merged**
