### PR TITLE
Refactor and add RadioButton component

### PR DESCRIPTION
**Pull request by Horat1us**
See example and readme for details

### CODE REVIEW

**Comment by nkbt** [comment]
Was it meant to be a pr for different fork?

**Comment by Horat1us** [comment]
This fork has 100% same API. If this pull request will be accepted I will use this repository.

**Comment by nkbt** [comment]
To me this is a completely different API and a different library. The fact that is still keeps the previous code to serve old API does not change it.

PS: and just in case all the naming and authors changed too...

Generally if the library has a different API it should be considered, well, a different library. You'd better not have 2 different APIs doing same thing in a single library.

**Comment by danielberndt** [comment]
I believe react-radio-group's goal is to be as low level as possible so others can build on top of it. While your additions might be helpful to a lot of people, I don't think it's a generic enough solution to be helpful for everyone. So I'm in favour of you releasing this as a separate library and then maybe the README of react-radio-group could add a list of projects which add useful functionality.

**Comment by nkbt** [comment]
One of main goal was to explore this new (for the time) approach of rendering children as function. Plus what @danielberndt said

Sorry, but will close the pr

**Pull request closed without merging**
